/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Paneles;

import GUI.Paneles.JDialog_GUI.P2_NuevoContrato_ConReserva;
import GUI.Paneles.JDialog_GUI.P2_NuevoContrato_SinReserva;
import GUI.Paneles.JDialog_GUI.P5_NuevoReserva;
import Gestion_Contratos.ContratoAlquiler;
import Gestion_Reservas.Reserva;
import Gestion_Reservas.ReservaMetodos;
import Gestion_Vehiculos.Vehiculo;
import Gestion_Vehiculos.VehiculosHashMap;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author isaac
 */
public class P2 extends javax.swing.JPanel {
private TableRowSorter<DefaultTableModel> sorter;
    /**
     * Creates new form P2
     */
    public P2() {
        initComponents();
       cargarTablas();
       DefaultTableModel modelo = (DefaultTableModel) TablaCont.getModel();
        sorter = new TableRowSorter<>(modelo);
        TablaCont.setRowSorter(sorter);

       inicializar();
    }
    
    
    
    
    private void inicializar(){
    
    Buscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filtrarTabla();
        }
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filtrarTabla();
        }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filtrarTabla();
        }

        private void filtrarTabla() {
            String texto = Buscar.getText();
            if (texto.trim().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
            }
        }
    });

    TablaCont.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int fila = TablaCont.getSelectedRow();
            if (fila != -1) {
                int filaModelo = TablaCont.convertRowIndexToModel(fila);
                String numeroContrato = (String) TablaCont.getModel().getValueAt(filaModelo, 0);
                Selecionar.setText("Seleccionado: " + numeroContrato);
            } else {
                Selecionar.setText("Seleccionado:");
            }
        }
    });
       }
  
    public void actualizartablas(){
    cargarTablas();
}

   
   private void cargarTablas() {
    DefaultTableModel modeloContratos = (DefaultTableModel) TablaCont.getModel();
    modeloContratos.setRowCount(0);
    ArrayList<ContratoAlquiler> contratos = ContratoAlquiler.getContratos();
    for (ContratoAlquiler c : contratos) {
        Object[] fila = new Object[] {
            c.getNumeroContrato(),
            c.getCliente().getCedula(),
            c.getVehiculo().getPlaca(),
            c.getFechaInicio().toString(),
            c.getFechaFin().toString(),
            c.getMonto(),
            c.getEstado()
        };
        modeloContratos.addRow(fila);
    }
 }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCont = new javax.swing.JTable();
        Buscar = new javax.swing.JTextField();
        Selecionar = new javax.swing.JTextField();
        btnEditarContrato = new javax.swing.JButton();
        btnNuevoContrato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(870, 473));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 470));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(840, 440));

        TablaCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Vehiculo", "Inicio", "Finalizacion", "Monto", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCont.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaCont);
        if (TablaCont.getColumnModel().getColumnCount() > 0) {
            TablaCont.getColumnModel().getColumn(0).setResizable(false);
            TablaCont.getColumnModel().getColumn(1).setResizable(false);
            TablaCont.getColumnModel().getColumn(2).setResizable(false);
            TablaCont.getColumnModel().getColumn(3).setResizable(false);
            TablaCont.getColumnModel().getColumn(4).setResizable(false);
            TablaCont.getColumnModel().getColumn(5).setResizable(false);
            TablaCont.getColumnModel().getColumn(6).setResizable(false);
        }

        Buscar.setText("Buscar :");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Selecionar.setEditable(false);
        Selecionar.setText("Seleccionado :");
        Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });

        btnEditarContrato.setText("Cancelar");
        btnEditarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContratoActionPerformed(evt);
            }
        });

        btnNuevoContrato.setText("Nuevo Contrato");
        btnNuevoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoContratoActionPerformed(evt);
            }
        });

        jButton1.setText("Nuevo Contraro sin reserva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizarcontrarto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEditarContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(Buscar)
                    .addComponent(Selecionar))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarContrato)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contratos", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame frame = null;
        if (window instanceof java.awt.Frame) {
            frame = (java.awt.Frame) window;
        }
        P2_NuevoContrato_SinReserva dialog = new P2_NuevoContrato_SinReserva(frame, true);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        cargarTablas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNuevoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoContratoActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame frame = null;
        if (window instanceof java.awt.Frame) {
            frame = (java.awt.Frame) window;
        }
        P2_NuevoContrato_ConReserva dialog = new P2_NuevoContrato_ConReserva(frame, true);
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
        cargarTablas();                  
    }//GEN-LAST:event_btnNuevoContratoActionPerformed

    private void btnEditarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContratoActionPerformed
            int filaSeleccionada = TablaCont.getSelectedRow();
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un contrato de la tabla.");
        return;
    }

    String numeroContrato = (String) TablaCont.getValueAt(filaSeleccionada, 0);
    String estadoActual = (String) TablaCont.getValueAt(filaSeleccionada, 6);

    if ("Finalizado".equalsIgnoreCase(estadoActual)) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se puede cancelar un contrato finalizado.");
        return;
    }

    String resultado = ContratoAlquiler.cancelarContrato(numeroContrato);
    javax.swing.JOptionPane.showMessageDialog(this, resultado);
    cargarTablas();
    }//GEN-LAST:event_btnEditarContratoActionPerformed

    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecionarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int filaSeleccionada = TablaCont.getSelectedRow();
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un contrato de la tabla.");
        return;
    }

    String numeroContrato = (String) TablaCont.getValueAt(filaSeleccionada, 0);
    String resultado = ContratoAlquiler.finalizarContrato(numeroContrato);
    javax.swing.JOptionPane.showMessageDialog(this, resultado);
    cargarTablas();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JTextField Selecionar;
    private javax.swing.JTable TablaCont;
    private javax.swing.JButton btnEditarContrato;
    private javax.swing.JButton btnNuevoContrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
