/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Paneles;

import GUI.Paneles.JDialog_GUI.P2_NuevoContrato_SinReserva;
import GUI.Paneles.JDialog_GUI.P5_ActualizarR;
import GUI.Paneles.JDialog_GUI.P5_NuevoReserva;
import Gestion_Contratos.ContratoAlquiler;
import Gestion_Reservas.Reserva;
import Gestion_Reservas.ReservaMetodos;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author isaac
 */
public class P5 extends javax.swing.JPanel {
private TableRowSorter<DefaultTableModel> sorterReservas;
private TableRowSorter<DefaultTableModel> sorterEspera;

    /**
     * Creates new form P2
     */
    public P5() {
        initComponents();
        cargarTablas();

// Mostrar ID seleccionado en jTextField1
Tablareserva.getSelectionModel().addListSelectionListener(e -> {
    int fila = Tablareserva.getSelectedRow();
    if (fila != -1)
        jTextField1.setText("Seleccionado: " + Tablareserva.getValueAt(fila, 0));
});

TablareservaEspera.getSelectionModel().addListSelectionListener(e -> {
    int fila = TablareservaEspera.getSelectedRow();
    if (fila != -1)
        jTextField1.setText("Seleccionado: " + TablareservaEspera.getValueAt(fila, 0));
});

    }

    
    public void actualizartablas(){
    cargarTablas();
}
    
   
 private void cargarTablas() {
    DefaultTableModel modeloReservas = (DefaultTableModel) Tablareserva.getModel();
    modeloReservas.setRowCount(0);
    List<Reserva> reservas = ReservaMetodos.getReservas();
    for (Reserva r : reservas) {
        if (!"En espera".equalsIgnoreCase(r.getEstado())) {
            modeloReservas.addRow(new Object[]{
                r.getId(),
                r.getClienteCedula(),
                r.getVehiculoPlaca(),
                r.getInicio().toString(),
                r.getFin().toString(),
                r.getEstado()
            });
        }
    }
    sorterReservas = new TableRowSorter<>(modeloReservas);
    Tablareserva.setRowSorter(sorterReservas);

    DefaultTableModel modeloEspera = (DefaultTableModel) TablareservaEspera.getModel();
    modeloEspera.setRowCount(0);
    Queue<Reserva> colaEspera = ReservaMetodos.getColaEspera();
    for (Reserva r : colaEspera) {
        modeloEspera.addRow(new Object[]{
            r.getId(),
            r.getClienteCedula(),
            r.getVehiculoPlaca(),
            r.getInicio().toString(),
            r.getFin().toString(),
            r.getEstado()
        });
    }
    sorterEspera = new TableRowSorter<>(modeloEspera);
    TablareservaEspera.setRowSorter(sorterEspera);
}


 
 
 
 
 
 
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablareserva = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnBuscarReserva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablareservaEspera = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        btnBuscarReserva1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(870, 473));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 470));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(840, 440));

        Tablareserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Vehiculo", "Inicio ", "Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablareserva.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tablareserva);
        if (Tablareserva.getColumnModel().getColumnCount() > 0) {
            Tablareserva.getColumnModel().getColumn(0).setResizable(false);
            Tablareserva.getColumnModel().getColumn(1).setResizable(false);
            Tablareserva.getColumnModel().getColumn(2).setResizable(false);
            Tablareserva.getColumnModel().getColumn(3).setResizable(false);
            Tablareserva.getColumnModel().getColumn(4).setResizable(false);
            Tablareserva.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nueva Reserva");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Seleccionado :");

        btnBuscarReserva.setText("Buscar :");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(btnBuscarReserva)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Reservas", jPanel2);

        TablareservaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Vehiculo", "Inicio ", "Final", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablareservaEspera.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TablareservaEspera);
        if (TablareservaEspera.getColumnModel().getColumnCount() > 0) {
            TablareservaEspera.getColumnModel().getColumn(0).setResizable(false);
            TablareservaEspera.getColumnModel().getColumn(1).setResizable(false);
            TablareservaEspera.getColumnModel().getColumn(2).setResizable(false);
            TablareservaEspera.getColumnModel().getColumn(3).setResizable(false);
            TablareservaEspera.getColumnModel().getColumn(4).setResizable(false);
            TablareservaEspera.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton5.setText("Cancelar Reserva en espera");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnBuscarReserva1.setText("Buscar :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de espera", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame frame = null;
    if (window instanceof java.awt.Frame) {
        frame = (java.awt.Frame) window;
    }
    P5_NuevoReserva dialog = new P5_NuevoReserva(frame, true);
    dialog.setLocationRelativeTo(frame);
    dialog.setVisible(true);
    cargarTablas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    int fila = TablareservaEspera.getSelectedRow();
    if (fila != -1) {
        String id = TablareservaEspera.getValueAt(fila, 0).toString();
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "¿Cancelar reserva en espera?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            if (ReservaMetodos.cancelarReservaEnEspera(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cancelada.");
                cargarTablas();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cancelar.");
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una reserva en espera.");
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
         int fila = Tablareserva.getSelectedRow();
    
    if (fila != -1) {
        String id = Tablareserva.getValueAt(fila, 0).toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de cancelar esta reserva?",
            "Confirmar cancelación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            boolean cancelado = ReservaMetodos.cancelar(id);
            if (cancelado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Reserva cancelada con éxito.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cancelar. La reserva ya inició o no existe.");
            }
            cargarTablas(); // Actualizar tabla después de cancelar
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una reserva para cancelar.");
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame frame = null;
    if (window instanceof java.awt.Frame) {
        frame = (java.awt.Frame) window;
    }
    P5_ActualizarR dialog = new P5_ActualizarR(frame, true);
    dialog.setLocationRelativeTo(frame);
    dialog.setVisible(true);
    cargarTablas();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablareserva;
    private javax.swing.JTable TablareservaEspera;
    private javax.swing.JTextField btnBuscarReserva;
    private javax.swing.JTextField btnBuscarReserva1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
